# Generated by Django 5.0 on 2025-01-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationhistory',
            name='mol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calculationhistory',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
